// ==============================================================
// Generated by Vitis HLS v2023.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_module_OP_AL_32I (
        ap_ready,
        opcode_val,
        func7_val,
        func3_val,
        op1_val,
        op2_val,
        ap_return
);


output   ap_ready;
input  [5:0] opcode_val;
input  [6:0] func7_val;
input  [2:0] func3_val;
input  [31:0] op1_val;
input  [31:0] op2_val;
output  [31:0] ap_return;

wire   [30:0] grp_fu_237_p2;
reg   [30:0] ap_phi_mux_rd_val_5_phi_fu_81_p46;
wire   [5:0] opcode_val_read_read_fu_72_p2;
wire   [2:0] func3_val_read_read_fu_60_p2;
wire   [30:0] grp_fu_207_p2;
wire   [30:0] grp_fu_213_p2;
wire   [30:0] zext_ln7_1_fu_297_p1;
wire   [30:0] zext_ln7_fu_302_p1;
wire   [30:0] trunc_ln7_fu_321_p1;
wire   [30:0] grp_fu_231_p2;
wire   [6:0] func7_val_read_read_fu_66_p2;
wire   [30:0] trunc_ln7_5_fu_273_p1;
wire   [30:0] trunc_ln7_4_fu_292_p1;
wire   [30:0] trunc_ln7_3_fu_340_p1;
wire   [30:0] rd_val_16_fu_345_p2;
wire   [30:0] trunc_ln7_2_fu_366_p1;
wire   [30:0] zext_ln7_3_fu_371_p1;
wire   [30:0] zext_ln7_2_fu_376_p1;
wire   [30:0] trunc_ln7_1_fu_395_p1;
reg   [0:0] ap_phi_mux_error_phi_fu_136_p46;
wire   [30:0] empty_128_fu_251_p1;
wire   [30:0] empty_fu_243_p1;
wire   [4:0] op2_5_fu_259_p1;
wire   [31:0] zext_ln109_1_fu_263_p1;
wire   [31:0] rd_val_19_fu_267_p2;
wire   [4:0] op2_4_fu_278_p1;
wire   [31:0] zext_ln105_1_fu_282_p1;
wire   [31:0] rd_val_18_fu_286_p2;
wire   [0:0] grp_fu_219_p2;
wire   [0:0] grp_fu_225_p2;
wire   [4:0] op2_fu_307_p1;
wire   [31:0] zext_ln88_fu_311_p1;
wire   [31:0] rd_val_2_fu_315_p2;
wire   [4:0] op2_3_fu_326_p1;
wire   [31:0] zext_ln109_fu_330_p1;
wire   [31:0] rd_val_17_fu_334_p2;
wire   [4:0] op2_2_fu_352_p1;
wire   [31:0] zext_ln105_fu_356_p1;
wire   [31:0] rd_val_14_fu_360_p2;
wire   [4:0] op2_1_fu_381_p1;
wire   [31:0] zext_ln88_1_fu_385_p1;
wire   [31:0] rd_val_10_fu_389_p2;
wire    ap_ce_reg;

always @ (*) begin
    if (((~(func7_val_read_read_fu_66_p2 == 7'd32) & ~(func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd5) & (opcode_val_read_read_fu_72_p2 == 6'd19)) | (~(func7_val_read_read_fu_66_p2 == 7'd32) & ~(func7_val_read_read_fu_66_p2 == 7'd0) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | (~(opcode_val_read_read_fu_72_p2 == 6'd51) & ~(opcode_val_read_read_fu_72_p2 == 6'd19)) | (~(func3_val_read_read_fu_60_p2 == 3'd5) & ~(func3_val_read_read_fu_60_p2 == 3'd0) & (func7_val_read_read_fu_66_p2 == 7'd32) & (opcode_val_read_read_fu_72_p2 == 6'd51)))) begin
        ap_phi_mux_error_phi_fu_136_p46 = 1'd1;
    end else if ((((func7_val_read_read_fu_66_p2 == 7'd32) & (func3_val_read_read_fu_60_p2 == 3'd5) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func7_val_read_read_fu_66_p2 == 7'd32) & (func3_val_read_read_fu_60_p2 == 3'd5) & (opcode_val_read_read_fu_72_p2 == 6'd19)) | ((func7_val_read_read_fu_66_p2 == 7'd32) & (func3_val_read_read_fu_60_p2 == 3'd0) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd5) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd5) & (opcode_val_read_read_fu_72_p2 == 6'd19)) | ((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd0) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd1) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd2) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func7_val_read_read_fu_66_p2 
    == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd3) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd4) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd6) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd7) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func3_val_read_read_fu_60_p2 == 3'd0) & (opcode_val_read_read_fu_72_p2 == 6'd19)) | ((func3_val_read_read_fu_60_p2 == 3'd1) & (opcode_val_read_read_fu_72_p2 == 6'd19)) | ((func3_val_read_read_fu_60_p2 == 3'd2) & (opcode_val_read_read_fu_72_p2 == 6'd19)) | ((func3_val_read_read_fu_60_p2 == 3'd3) & (opcode_val_read_read_fu_72_p2 == 6'd19)) | ((func3_val_read_read_fu_60_p2 == 3'd4) & (opcode_val_read_read_fu_72_p2 == 6'd19)) | ((func3_val_read_read_fu_60_p2 == 3'd6) & (opcode_val_read_read_fu_72_p2 == 6'd19)) | ((func3_val_read_read_fu_60_p2 == 
    3'd7) & (opcode_val_read_read_fu_72_p2 == 6'd19)))) begin
        ap_phi_mux_error_phi_fu_136_p46 = 1'd0;
    end else begin
        ap_phi_mux_error_phi_fu_136_p46 = 'bx;
    end
end

always @ (*) begin
    if (((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd1) & (opcode_val_read_read_fu_72_p2 == 6'd51))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = trunc_ln7_1_fu_395_p1;
    end else if (((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd2) & (opcode_val_read_read_fu_72_p2 == 6'd51))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = zext_ln7_2_fu_376_p1;
    end else if (((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd3) & (opcode_val_read_read_fu_72_p2 == 6'd51))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = zext_ln7_3_fu_371_p1;
    end else if (((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd5) & (opcode_val_read_read_fu_72_p2 == 6'd51))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = trunc_ln7_2_fu_366_p1;
    end else if (((func7_val_read_read_fu_66_p2 == 7'd32) & (func3_val_read_read_fu_60_p2 == 3'd0) & (opcode_val_read_read_fu_72_p2 == 6'd51))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = rd_val_16_fu_345_p2;
    end else if (((func7_val_read_read_fu_66_p2 == 7'd32) & (func3_val_read_read_fu_60_p2 == 3'd5) & (opcode_val_read_read_fu_72_p2 == 6'd51))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = trunc_ln7_3_fu_340_p1;
    end else if (((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd5) & (opcode_val_read_read_fu_72_p2 == 6'd19))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = trunc_ln7_4_fu_292_p1;
    end else if (((func7_val_read_read_fu_66_p2 == 7'd32) & (func3_val_read_read_fu_60_p2 == 3'd5) & (opcode_val_read_read_fu_72_p2 == 6'd19))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = trunc_ln7_5_fu_273_p1;
    end else if ((((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd0) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func3_val_read_read_fu_60_p2 == 3'd0) & (opcode_val_read_read_fu_72_p2 == 6'd19)))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = grp_fu_231_p2;
    end else if (((func3_val_read_read_fu_60_p2 == 3'd1) & (opcode_val_read_read_fu_72_p2 == 6'd19))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = trunc_ln7_fu_321_p1;
    end else if (((func3_val_read_read_fu_60_p2 == 3'd2) & (opcode_val_read_read_fu_72_p2 == 6'd19))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = zext_ln7_fu_302_p1;
    end else if (((func3_val_read_read_fu_60_p2 == 3'd3) & (opcode_val_read_read_fu_72_p2 == 6'd19))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = zext_ln7_1_fu_297_p1;
    end else if ((((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd4) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func3_val_read_read_fu_60_p2 == 3'd4) & (opcode_val_read_read_fu_72_p2 == 6'd19)))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = grp_fu_213_p2;
    end else if ((((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd6) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func3_val_read_read_fu_60_p2 == 3'd6) & (opcode_val_read_read_fu_72_p2 == 6'd19)))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = grp_fu_207_p2;
    end else if ((((func7_val_read_read_fu_66_p2 == 7'd0) & (func3_val_read_read_fu_60_p2 == 3'd7) & (opcode_val_read_read_fu_72_p2 == 6'd51)) | ((func3_val_read_read_fu_60_p2 == 3'd7) & (opcode_val_read_read_fu_72_p2 == 6'd19)))) begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = grp_fu_237_p2;
    end else begin
        ap_phi_mux_rd_val_5_phi_fu_81_p46 = 'bx;
    end
end

assign ap_ready = 1'b1;

assign empty_128_fu_251_p1 = op2_val[30:0];

assign empty_fu_243_p1 = op1_val[30:0];

assign grp_fu_207_p2 = (empty_fu_243_p1 | empty_128_fu_251_p1);

assign grp_fu_213_p2 = (empty_fu_243_p1 ^ empty_128_fu_251_p1);

assign grp_fu_219_p2 = ((op1_val < op2_val) ? 1'b1 : 1'b0);

assign grp_fu_225_p2 = (($signed(op1_val) < $signed(op2_val)) ? 1'b1 : 1'b0);

assign grp_fu_231_p2 = (empty_128_fu_251_p1 + empty_fu_243_p1);

assign grp_fu_237_p2 = (empty_fu_243_p1 & empty_128_fu_251_p1);

assign op2_1_fu_381_p1 = op2_val[4:0];

assign op2_2_fu_352_p1 = op2_val[4:0];

assign op2_3_fu_326_p1 = op2_val[4:0];

assign op2_4_fu_278_p1 = op2_val[4:0];

assign op2_5_fu_259_p1 = op2_val[4:0];

assign op2_fu_307_p1 = op2_val[4:0];

assign rd_val_10_fu_389_p2 = op1_val << zext_ln88_1_fu_385_p1;

assign rd_val_14_fu_360_p2 = op1_val >> zext_ln105_fu_356_p1;

assign rd_val_16_fu_345_p2 = (empty_fu_243_p1 - empty_128_fu_251_p1);

assign rd_val_17_fu_334_p2 = $signed(op1_val) >>> zext_ln109_fu_330_p1;

assign rd_val_18_fu_286_p2 = op1_val >> zext_ln105_1_fu_282_p1;

assign rd_val_19_fu_267_p2 = $signed(op1_val) >>> zext_ln109_1_fu_263_p1;

assign rd_val_2_fu_315_p2 = op1_val << zext_ln88_fu_311_p1;

assign trunc_ln7_1_fu_395_p1 = rd_val_10_fu_389_p2[30:0];

assign trunc_ln7_2_fu_366_p1 = rd_val_14_fu_360_p2[30:0];

assign trunc_ln7_3_fu_340_p1 = rd_val_17_fu_334_p2[30:0];

assign trunc_ln7_4_fu_292_p1 = rd_val_18_fu_286_p2[30:0];

assign trunc_ln7_5_fu_273_p1 = rd_val_19_fu_267_p2[30:0];

assign trunc_ln7_fu_321_p1 = rd_val_2_fu_315_p2[30:0];

assign zext_ln105_1_fu_282_p1 = op2_4_fu_278_p1;

assign zext_ln105_fu_356_p1 = op2_2_fu_352_p1;

assign zext_ln109_1_fu_263_p1 = op2_5_fu_259_p1;

assign zext_ln109_fu_330_p1 = op2_3_fu_326_p1;

assign zext_ln7_1_fu_297_p1 = grp_fu_219_p2;

assign zext_ln7_2_fu_376_p1 = grp_fu_225_p2;

assign zext_ln7_3_fu_371_p1 = grp_fu_219_p2;

assign zext_ln7_fu_302_p1 = grp_fu_225_p2;

assign zext_ln88_1_fu_385_p1 = op2_1_fu_381_p1;

assign zext_ln88_fu_311_p1 = op2_fu_307_p1;

assign ap_return = {{ap_phi_mux_rd_val_5_phi_fu_81_p46}, {ap_phi_mux_error_phi_fu_136_p46}};

assign func3_val_read_read_fu_60_p2 = func3_val;

assign func7_val_read_read_fu_66_p2 = func7_val;

assign opcode_val_read_read_fu_72_p2 = opcode_val;

endmodule //top_module_OP_AL_32I
