-- ==============================================================
-- Generated by Vitis HLS v2023.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hart_OP_AL_32I is
port (
    ap_ready : OUT STD_LOGIC;
    opcode_val : IN STD_LOGIC_VECTOR (5 downto 0);
    func7_val : IN STD_LOGIC_VECTOR (6 downto 0);
    func3_val : IN STD_LOGIC_VECTOR (2 downto 0);
    op1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    op2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of hart_OP_AL_32I is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_33 : STD_LOGIC_VECTOR (5 downto 0) := "110011";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv7_20 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal grp_fu_237_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_mux_rd_val_5_phi_fu_81_p46 : STD_LOGIC_VECTOR (30 downto 0);
    signal opcode_val_read_read_fu_72_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal func3_val_read_read_fu_60_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_207_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_213_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln7_1_fu_297_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln7_fu_302_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln7_fu_321_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_231_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal func7_val_read_read_fu_66_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln7_5_fu_273_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln7_4_fu_292_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln7_3_fu_340_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal rd_val_16_fu_345_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln7_2_fu_366_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln7_3_fu_371_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln7_2_fu_376_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln7_1_fu_395_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_mux_error_phi_fu_136_p46 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_61_fu_251_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_fu_243_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal op2_6_fu_259_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln109_1_fu_263_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_19_fu_267_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_5_fu_278_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln105_1_fu_282_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_18_fu_286_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_219_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal op2_fu_307_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln88_fu_311_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_2_fu_315_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_4_fu_326_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln109_fu_330_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_17_fu_334_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_3_fu_352_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln105_fu_356_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_14_fu_360_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal op2_2_fu_381_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln88_1_fu_385_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rd_val_10_fu_389_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_phi_mux_error_phi_fu_136_p46_assign_proc : process(opcode_val_read_read_fu_72_p2, func3_val_read_read_fu_60_p2, func7_val_read_read_fu_66_p2)
    begin
        if (((not((func7_val_read_read_fu_66_p2 = ap_const_lv7_20)) and not((func7_val_read_read_fu_66_p2 = ap_const_lv7_0)) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)) or (not((func7_val_read_read_fu_66_p2 = ap_const_lv7_20)) and not((func7_val_read_read_fu_66_p2 = ap_const_lv7_0)) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or (not((opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) and not((opcode_val_read_read_fu_72_p2 = ap_const_lv6_13))) or (not((func3_val_read_read_fu_60_p2 = ap_const_lv3_5)) and not((func3_val_read_read_fu_60_p2 = ap_const_lv3_0)) and (func7_val_read_read_fu_66_p2 = ap_const_lv7_20) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)))) then 
            ap_phi_mux_error_phi_fu_136_p46 <= ap_const_lv1_1;
        elsif ((((func7_val_read_read_fu_66_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func7_val_read_read_fu_66_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)) or ((func7_val_read_read_fu_66_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_0) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)) or ((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_0) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 
    = ap_const_lv3_1) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_2) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_3) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_4) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_6) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_7) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func3_val_read_read_fu_60_p2 = ap_const_lv3_0) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)) or ((func3_val_read_read_fu_60_p2 = ap_const_lv3_1) 
    and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)) or ((func3_val_read_read_fu_60_p2 = ap_const_lv3_2) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)) or ((func3_val_read_read_fu_60_p2 = ap_const_lv3_3) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)) or ((func3_val_read_read_fu_60_p2 = ap_const_lv3_4) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)) or ((func3_val_read_read_fu_60_p2 = ap_const_lv3_6) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)) or ((func3_val_read_read_fu_60_p2 = ap_const_lv3_7) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)))) then 
            ap_phi_mux_error_phi_fu_136_p46 <= ap_const_lv1_0;
        else 
            ap_phi_mux_error_phi_fu_136_p46 <= "X";
        end if; 
    end process;


    ap_phi_mux_rd_val_5_phi_fu_81_p46_assign_proc : process(grp_fu_237_p2, opcode_val_read_read_fu_72_p2, func3_val_read_read_fu_60_p2, grp_fu_207_p2, grp_fu_213_p2, zext_ln7_1_fu_297_p1, zext_ln7_fu_302_p1, trunc_ln7_fu_321_p1, grp_fu_231_p2, func7_val_read_read_fu_66_p2, trunc_ln7_5_fu_273_p1, trunc_ln7_4_fu_292_p1, trunc_ln7_3_fu_340_p1, rd_val_16_fu_345_p2, trunc_ln7_2_fu_366_p1, zext_ln7_3_fu_371_p1, zext_ln7_2_fu_376_p1, trunc_ln7_1_fu_395_p1)
    begin
        if (((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_1) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= trunc_ln7_1_fu_395_p1;
        elsif (((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_2) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= zext_ln7_2_fu_376_p1;
        elsif (((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_3) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= zext_ln7_3_fu_371_p1;
        elsif (((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= trunc_ln7_2_fu_366_p1;
        elsif (((func7_val_read_read_fu_66_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_0) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= rd_val_16_fu_345_p2;
        elsif (((func7_val_read_read_fu_66_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= trunc_ln7_3_fu_340_p1;
        elsif (((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= trunc_ln7_4_fu_292_p1;
        elsif (((func7_val_read_read_fu_66_p2 = ap_const_lv7_20) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_5) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= trunc_ln7_5_fu_273_p1;
        elsif ((((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_0) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func3_val_read_read_fu_60_p2 = ap_const_lv3_0) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= grp_fu_231_p2;
        elsif (((func3_val_read_read_fu_60_p2 = ap_const_lv3_1) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= trunc_ln7_fu_321_p1;
        elsif (((func3_val_read_read_fu_60_p2 = ap_const_lv3_2) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= zext_ln7_fu_302_p1;
        elsif (((func3_val_read_read_fu_60_p2 = ap_const_lv3_3) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= zext_ln7_1_fu_297_p1;
        elsif ((((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_4) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func3_val_read_read_fu_60_p2 = ap_const_lv3_4) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= grp_fu_213_p2;
        elsif ((((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_6) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func3_val_read_read_fu_60_p2 = ap_const_lv3_6) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= grp_fu_207_p2;
        elsif ((((func7_val_read_read_fu_66_p2 = ap_const_lv7_0) and (func3_val_read_read_fu_60_p2 = ap_const_lv3_7) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_33)) or ((func3_val_read_read_fu_60_p2 = ap_const_lv3_7) and (opcode_val_read_read_fu_72_p2 = ap_const_lv6_13)))) then 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= grp_fu_237_p2;
        else 
            ap_phi_mux_rd_val_5_phi_fu_81_p46 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    ap_ready <= ap_const_logic_1;
    ap_return <= (ap_phi_mux_rd_val_5_phi_fu_81_p46 & ap_phi_mux_error_phi_fu_136_p46);
    empty_61_fu_251_p1 <= op2_val(31 - 1 downto 0);
    empty_fu_243_p1 <= op1_val(31 - 1 downto 0);
    func3_val_read_read_fu_60_p2 <= func3_val;
    func7_val_read_read_fu_66_p2 <= func7_val;
    grp_fu_207_p2 <= (empty_fu_243_p1 or empty_61_fu_251_p1);
    grp_fu_213_p2 <= (empty_fu_243_p1 xor empty_61_fu_251_p1);
    grp_fu_219_p2 <= "1" when (unsigned(op1_val) < unsigned(op2_val)) else "0";
    grp_fu_225_p2 <= "1" when (signed(op1_val) < signed(op2_val)) else "0";
    grp_fu_231_p2 <= std_logic_vector(unsigned(empty_61_fu_251_p1) + unsigned(empty_fu_243_p1));
    grp_fu_237_p2 <= (empty_fu_243_p1 and empty_61_fu_251_p1);
    op2_2_fu_381_p1 <= op2_val(5 - 1 downto 0);
    op2_3_fu_352_p1 <= op2_val(5 - 1 downto 0);
    op2_4_fu_326_p1 <= op2_val(5 - 1 downto 0);
    op2_5_fu_278_p1 <= op2_val(5 - 1 downto 0);
    op2_6_fu_259_p1 <= op2_val(5 - 1 downto 0);
    op2_fu_307_p1 <= op2_val(5 - 1 downto 0);
    opcode_val_read_read_fu_72_p2 <= opcode_val;
    rd_val_10_fu_389_p2 <= std_logic_vector(shift_left(unsigned(op1_val),to_integer(unsigned('0' & zext_ln88_1_fu_385_p1(31-1 downto 0)))));
    rd_val_14_fu_360_p2 <= std_logic_vector(shift_right(unsigned(op1_val),to_integer(unsigned('0' & zext_ln105_fu_356_p1(31-1 downto 0)))));
    rd_val_16_fu_345_p2 <= std_logic_vector(unsigned(empty_fu_243_p1) - unsigned(empty_61_fu_251_p1));
    rd_val_17_fu_334_p2 <= std_logic_vector(shift_right(signed(op1_val),to_integer(unsigned('0' & zext_ln109_fu_330_p1(31-1 downto 0)))));
    rd_val_18_fu_286_p2 <= std_logic_vector(shift_right(unsigned(op1_val),to_integer(unsigned('0' & zext_ln105_1_fu_282_p1(31-1 downto 0)))));
    rd_val_19_fu_267_p2 <= std_logic_vector(shift_right(signed(op1_val),to_integer(unsigned('0' & zext_ln109_1_fu_263_p1(31-1 downto 0)))));
    rd_val_2_fu_315_p2 <= std_logic_vector(shift_left(unsigned(op1_val),to_integer(unsigned('0' & zext_ln88_fu_311_p1(31-1 downto 0)))));
    trunc_ln7_1_fu_395_p1 <= rd_val_10_fu_389_p2(31 - 1 downto 0);
    trunc_ln7_2_fu_366_p1 <= rd_val_14_fu_360_p2(31 - 1 downto 0);
    trunc_ln7_3_fu_340_p1 <= rd_val_17_fu_334_p2(31 - 1 downto 0);
    trunc_ln7_4_fu_292_p1 <= rd_val_18_fu_286_p2(31 - 1 downto 0);
    trunc_ln7_5_fu_273_p1 <= rd_val_19_fu_267_p2(31 - 1 downto 0);
    trunc_ln7_fu_321_p1 <= rd_val_2_fu_315_p2(31 - 1 downto 0);
    zext_ln105_1_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(op2_5_fu_278_p1),32));
    zext_ln105_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(op2_3_fu_352_p1),32));
    zext_ln109_1_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(op2_6_fu_259_p1),32));
    zext_ln109_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(op2_4_fu_326_p1),32));
    zext_ln7_1_fu_297_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_219_p2),31));
    zext_ln7_2_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_225_p2),31));
    zext_ln7_3_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_219_p2),31));
    zext_ln7_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_225_p2),31));
    zext_ln88_1_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(op2_2_fu_381_p1),32));
    zext_ln88_fu_311_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(op2_fu_307_p1),32));
end behav;
