-- ==============================================================
-- Generated by Vitis HLS v2023.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_module_hart is
port (
    ap_ready : OUT STD_LOGIC;
    inst_val : IN STD_LOGIC_VECTOR (31 downto 0);
    r1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    r2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    pc_val : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of top_module_hart is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv7_6F : STD_LOGIC_VECTOR (6 downto 0) := "1101111";
    constant ap_const_lv7_17 : STD_LOGIC_VECTOR (6 downto 0) := "0010111";
    constant ap_const_lv7_37 : STD_LOGIC_VECTOR (6 downto 0) := "0110111";
    constant ap_const_lv7_13 : STD_LOGIC_VECTOR (6 downto 0) := "0010011";
    constant ap_const_lv7_33 : STD_LOGIC_VECTOR (6 downto 0) := "0110011";
    constant ap_const_lv7_67 : STD_LOGIC_VECTOR (6 downto 0) := "1100111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_63 : STD_LOGIC_VECTOR (6 downto 0) := "1100011";
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv6_33 : STD_LOGIC_VECTOR (5 downto 0) := "110011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv13_4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal grp_OP_AL_32I_fu_187_ap_ready : STD_LOGIC;
    signal grp_OP_AL_32I_fu_187_opcode_val : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_OP_AL_32I_fu_187_func7_val : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_OP_AL_32I_fu_187_func3_val : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_OP_AL_32I_fu_187_op2_val : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_OP_AL_32I_fu_187_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_200_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_phi_ln83_phi_fu_141_p18 : STD_LOGIC_VECTOR (31 downto 0);
    signal opcode_fu_248_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln80_fu_440_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal imm_20_U_fu_350_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln53_fu_608_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln48_fu_636_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln86_4_fu_433_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_phi_ln83_1_phi_fu_166_p18 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln86_6_fu_601_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln86_1_fu_627_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln1_fu_655_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_422_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_411_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal func3_fu_252_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln37_fu_285_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln67_3_fu_561_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_4_fu_575_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_2_fu_547_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_1_fu_533_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_fu_519_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal offset_2_fu_275_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_1_fu_298_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_290_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_316_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_5_fu_306_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_6_fu_340_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_s_fu_377_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_369_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_359_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal offset_1_fu_387_p6 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln86_5_fu_405_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln42_fu_401_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln68_fu_447_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal offset_3_fu_326_p6 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln69_fu_461_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln71_fu_483_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln73_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal returnval_7_fu_511_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal returnval_6_fu_497_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal returnval_8_fu_525_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal returnval_5_fu_489_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal returnval_9_fu_539_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal returnval_4_fu_475_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal returnval_10_fu_553_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal returnval_3_fu_467_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal returnval_11_fu_567_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal returnval_2_fu_453_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal returnval_12_fu_581_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal returnval_fu_589_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln66_fu_597_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_228_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln86_1_fu_617_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln54_fu_613_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_238_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal or_ln86_fu_621_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln86_fu_645_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln49_fu_641_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln86_2_fu_649_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component top_module_OP_AL_32I IS
    port (
        ap_ready : OUT STD_LOGIC;
        opcode_val : IN STD_LOGIC_VECTOR (5 downto 0);
        func7_val : IN STD_LOGIC_VECTOR (6 downto 0);
        func3_val : IN STD_LOGIC_VECTOR (2 downto 0);
        op1_val : IN STD_LOGIC_VECTOR (31 downto 0);
        op2_val : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_OP_AL_32I_fu_187 : component top_module_OP_AL_32I
    port map (
        ap_ready => grp_OP_AL_32I_fu_187_ap_ready,
        opcode_val => grp_OP_AL_32I_fu_187_opcode_val,
        func7_val => grp_OP_AL_32I_fu_187_func7_val,
        func3_val => grp_OP_AL_32I_fu_187_func3_val,
        op1_val => r1_val,
        op2_val => grp_OP_AL_32I_fu_187_op2_val,
        ap_return => grp_OP_AL_32I_fu_187_ap_return);




    add_ln80_fu_440_p2 <= std_logic_vector(unsigned(imm_20_U_fu_350_p3) + unsigned(pc_val));
    add_ln86_4_fu_433_p2 <= std_logic_vector(signed(sext_ln42_fu_401_p1) + signed(pc_val));
    add_ln86_5_fu_405_p2 <= std_logic_vector(signed(sext_ln37_fu_285_p1) + signed(pc_val));
    add_ln86_6_fu_601_p2 <= std_logic_vector(signed(sext_ln66_fu_597_p1) + signed(pc_val));

    ap_phi_mux_phi_ln83_1_phi_fu_166_p18_assign_proc : process(grp_fu_200_p2, opcode_fu_248_p1, grp_fu_211_p2, add_ln86_4_fu_433_p2, add_ln86_6_fu_601_p2, or_ln86_1_fu_627_p3, or_ln1_fu_655_p3, tmp_9_fu_422_p4, tmp_10_fu_411_p4)
    begin
        if (((grp_fu_211_p2 = ap_const_lv1_0) and (opcode_fu_248_p1 = ap_const_lv7_67))) then 
            ap_phi_mux_phi_ln83_1_phi_fu_166_p18 <= tmp_10_fu_411_p4;
        elsif (((grp_fu_211_p2 = ap_const_lv1_1) and (opcode_fu_248_p1 = ap_const_lv7_67))) then 
            ap_phi_mux_phi_ln83_1_phi_fu_166_p18 <= tmp_9_fu_422_p4;
        elsif ((opcode_fu_248_p1 = ap_const_lv7_33)) then 
            ap_phi_mux_phi_ln83_1_phi_fu_166_p18 <= or_ln1_fu_655_p3;
        elsif ((opcode_fu_248_p1 = ap_const_lv7_13)) then 
            ap_phi_mux_phi_ln83_1_phi_fu_166_p18 <= or_ln86_1_fu_627_p3;
        elsif ((opcode_fu_248_p1 = ap_const_lv7_63)) then 
            ap_phi_mux_phi_ln83_1_phi_fu_166_p18 <= add_ln86_6_fu_601_p2;
        elsif (((opcode_fu_248_p1 = ap_const_lv7_37) or (opcode_fu_248_p1 = ap_const_lv7_17))) then 
            ap_phi_mux_phi_ln83_1_phi_fu_166_p18 <= grp_fu_200_p2;
        elsif ((opcode_fu_248_p1 = ap_const_lv7_6F)) then 
            ap_phi_mux_phi_ln83_1_phi_fu_166_p18 <= add_ln86_4_fu_433_p2;
        else 
            ap_phi_mux_phi_ln83_1_phi_fu_166_p18 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_phi_ln83_phi_fu_141_p18_assign_proc : process(grp_fu_200_p2, opcode_fu_248_p1, add_ln80_fu_440_p2, imm_20_U_fu_350_p3, sext_ln53_fu_608_p1, sext_ln48_fu_636_p1, grp_fu_211_p2)
    begin
        if ((opcode_fu_248_p1 = ap_const_lv7_33)) then 
            ap_phi_mux_phi_ln83_phi_fu_141_p18 <= sext_ln48_fu_636_p1;
        elsif ((opcode_fu_248_p1 = ap_const_lv7_13)) then 
            ap_phi_mux_phi_ln83_phi_fu_141_p18 <= sext_ln53_fu_608_p1;
        elsif ((opcode_fu_248_p1 = ap_const_lv7_37)) then 
            ap_phi_mux_phi_ln83_phi_fu_141_p18 <= imm_20_U_fu_350_p3;
        elsif ((opcode_fu_248_p1 = ap_const_lv7_17)) then 
            ap_phi_mux_phi_ln83_phi_fu_141_p18 <= add_ln80_fu_440_p2;
        elsif (((opcode_fu_248_p1 = ap_const_lv7_6F) or ((grp_fu_211_p2 = ap_const_lv1_0) and (opcode_fu_248_p1 = ap_const_lv7_67)) or ((grp_fu_211_p2 = ap_const_lv1_1) and (opcode_fu_248_p1 = ap_const_lv7_67)))) then 
            ap_phi_mux_phi_ln83_phi_fu_141_p18 <= grp_fu_200_p2;
        else 
            ap_phi_mux_phi_ln83_phi_fu_141_p18 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    ap_ready <= ap_const_logic_1;
    ap_return_0 <= ap_phi_mux_phi_ln83_phi_fu_141_p18;
    ap_return_1 <= ap_phi_mux_phi_ln83_1_phi_fu_166_p18;
    func3_fu_252_p4 <= inst_val(14 downto 12);
    grp_OP_AL_32I_fu_187_func3_val <= inst_val(14 downto 12);
    grp_OP_AL_32I_fu_187_func7_val <= inst_val(31 downto 25);

    grp_OP_AL_32I_fu_187_op2_val_assign_proc : process(r2_val, opcode_fu_248_p1, sext_ln37_fu_285_p1)
    begin
        if ((opcode_fu_248_p1 = ap_const_lv7_33)) then 
            grp_OP_AL_32I_fu_187_op2_val <= r2_val;
        elsif ((opcode_fu_248_p1 = ap_const_lv7_13)) then 
            grp_OP_AL_32I_fu_187_op2_val <= sext_ln37_fu_285_p1;
        else 
            grp_OP_AL_32I_fu_187_op2_val <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_OP_AL_32I_fu_187_opcode_val_assign_proc : process(opcode_fu_248_p1)
    begin
        if ((opcode_fu_248_p1 = ap_const_lv7_33)) then 
            grp_OP_AL_32I_fu_187_opcode_val <= ap_const_lv6_33;
        elsif ((opcode_fu_248_p1 = ap_const_lv7_13)) then 
            grp_OP_AL_32I_fu_187_opcode_val <= ap_const_lv6_13;
        else 
            grp_OP_AL_32I_fu_187_opcode_val <= "XXXXXX";
        end if; 
    end process;

    grp_fu_200_p2 <= std_logic_vector(unsigned(pc_val) + unsigned(ap_const_lv32_4));
    grp_fu_211_p2 <= "1" when (func3_fu_252_p4 = ap_const_lv3_0) else "0";
    grp_fu_216_p2 <= "1" when (signed(r1_val) < signed(r2_val)) else "0";
    grp_fu_222_p2 <= "1" when (unsigned(r1_val) < unsigned(r2_val)) else "0";
    grp_fu_228_p4 <= grp_OP_AL_32I_fu_187_ap_return(31 downto 1);
    grp_fu_238_p4 <= grp_fu_200_p2(31 downto 1);
    icmp_ln67_1_fu_533_p2 <= "1" when (func3_fu_252_p4 = ap_const_lv3_6) else "0";
    icmp_ln67_2_fu_547_p2 <= "1" when (func3_fu_252_p4 = ap_const_lv3_5) else "0";
    icmp_ln67_3_fu_561_p2 <= "1" when (func3_fu_252_p4 = ap_const_lv3_4) else "0";
    icmp_ln67_4_fu_575_p2 <= "1" when (func3_fu_252_p4 = ap_const_lv3_1) else "0";
    icmp_ln67_fu_519_p2 <= "1" when (func3_fu_252_p4 = ap_const_lv3_7) else "0";
    icmp_ln68_fu_447_p2 <= "1" when (r1_val = r2_val) else "0";
    icmp_ln69_fu_461_p2 <= "0" when (r1_val = r2_val) else "1";
    imm_20_U_fu_350_p3 <= (tmp_6_fu_340_p4 & ap_const_lv12_0);
    offset_1_fu_387_p6 <= ((((tmp_1_fu_298_p3 & tmp_s_fu_377_p4) & tmp_2_fu_369_p3) & tmp_7_fu_359_p4) & ap_const_lv1_0);
    offset_2_fu_275_p4 <= inst_val(31 downto 20);
    offset_3_fu_326_p6 <= ((((tmp_1_fu_298_p3 & tmp_fu_290_p3) & tmp_3_fu_316_p4) & tmp_5_fu_306_p4) & ap_const_lv1_0);
    opcode_fu_248_p1 <= inst_val(7 - 1 downto 0);
    or_ln1_fu_655_p3 <= (grp_fu_238_p4 & or_ln86_2_fu_649_p2);
    or_ln86_1_fu_627_p3 <= (grp_fu_238_p4 & or_ln86_fu_621_p2);
    or_ln86_2_fu_649_p2 <= (trunc_ln86_fu_645_p1 or trunc_ln49_fu_641_p1);
    or_ln86_fu_621_p2 <= (trunc_ln86_1_fu_617_p1 or trunc_ln54_fu_613_p1);
    returnval_10_fu_553_p3 <= 
        returnval_5_fu_489_p3 when (icmp_ln67_2_fu_547_p2(0) = '1') else 
        returnval_9_fu_539_p3;
    returnval_11_fu_567_p3 <= 
        returnval_4_fu_475_p3 when (icmp_ln67_3_fu_561_p2(0) = '1') else 
        returnval_10_fu_553_p3;
    returnval_12_fu_581_p3 <= 
        returnval_3_fu_467_p3 when (icmp_ln67_4_fu_575_p2(0) = '1') else 
        returnval_11_fu_567_p3;
    returnval_2_fu_453_p3 <= 
        offset_3_fu_326_p6 when (icmp_ln68_fu_447_p2(0) = '1') else 
        ap_const_lv13_4;
    returnval_3_fu_467_p3 <= 
        offset_3_fu_326_p6 when (icmp_ln69_fu_461_p2(0) = '1') else 
        ap_const_lv13_4;
    returnval_4_fu_475_p3 <= 
        offset_3_fu_326_p6 when (grp_fu_216_p2(0) = '1') else 
        ap_const_lv13_4;
    returnval_5_fu_489_p3 <= 
        offset_3_fu_326_p6 when (xor_ln71_fu_483_p2(0) = '1') else 
        ap_const_lv13_4;
    returnval_6_fu_497_p3 <= 
        offset_3_fu_326_p6 when (grp_fu_222_p2(0) = '1') else 
        ap_const_lv13_4;
    returnval_7_fu_511_p3 <= 
        offset_3_fu_326_p6 when (xor_ln73_fu_505_p2(0) = '1') else 
        ap_const_lv13_4;
    returnval_8_fu_525_p3 <= 
        returnval_7_fu_511_p3 when (icmp_ln67_fu_519_p2(0) = '1') else 
        ap_const_lv13_1;
    returnval_9_fu_539_p3 <= 
        returnval_6_fu_497_p3 when (icmp_ln67_1_fu_533_p2(0) = '1') else 
        returnval_8_fu_525_p3;
    returnval_fu_589_p3 <= 
        returnval_2_fu_453_p3 when (grp_fu_211_p2(0) = '1') else 
        returnval_12_fu_581_p3;
        sext_ln37_fu_285_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(offset_2_fu_275_p4),32));

        sext_ln42_fu_401_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(offset_1_fu_387_p6),32));

        sext_ln48_fu_636_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_228_p4),32));

        sext_ln53_fu_608_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_228_p4),32));

        sext_ln66_fu_597_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(returnval_fu_589_p3),32));

    
    tmp_10_fu_411_p4_proc : process(add_ln86_5_fu_405_p2)
    begin
        tmp_10_fu_411_p4 <= add_ln86_5_fu_405_p2;
        tmp_10_fu_411_p4(0) <= ap_const_lv1_1(0);
    end process;

    tmp_1_fu_298_p3 <= inst_val(31 downto 31);
    tmp_2_fu_369_p3 <= inst_val(20 downto 20);
    tmp_3_fu_316_p4 <= inst_val(30 downto 25);
    tmp_5_fu_306_p4 <= inst_val(11 downto 8);
    tmp_6_fu_340_p4 <= inst_val(31 downto 12);
    tmp_7_fu_359_p4 <= inst_val(30 downto 21);
    
    tmp_9_fu_422_p4_proc : process(add_ln86_5_fu_405_p2)
    begin
        tmp_9_fu_422_p4 <= add_ln86_5_fu_405_p2;
        tmp_9_fu_422_p4(0) <= ap_const_lv1_0(0);
    end process;

    tmp_fu_290_p3 <= inst_val(7 downto 7);
    tmp_s_fu_377_p4 <= inst_val(19 downto 12);
    trunc_ln49_fu_641_p1 <= grp_OP_AL_32I_fu_187_ap_return(1 - 1 downto 0);
    trunc_ln54_fu_613_p1 <= grp_OP_AL_32I_fu_187_ap_return(1 - 1 downto 0);
    trunc_ln86_1_fu_617_p1 <= grp_fu_200_p2(1 - 1 downto 0);
    trunc_ln86_fu_645_p1 <= grp_fu_200_p2(1 - 1 downto 0);
    xor_ln71_fu_483_p2 <= (grp_fu_216_p2 xor ap_const_lv1_1);
    xor_ln73_fu_505_p2 <= (grp_fu_222_p2 xor ap_const_lv1_1);
end behav;
