// ==============================================================
// Generated by Vitis HLS v2023.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hart_hart,hls_ip_2023_2_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvf1517-3-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.581881,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=177,HLS_SYN_LUT=2229,HLS_VERSION=2023_2_2}" *)

module hart (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inst,
        pc,
        ap_return
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] inst;
input  [31:0] pc;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [4:0] rf_address0;
reg    rf_ce0;
reg    rf_we0;
reg   [31:0] rf_d0;
wire   [31:0] rf_q0;
reg   [4:0] rf_address1;
reg    rf_ce1;
reg    rf_we1;
reg   [31:0] rf_d1;
wire   [31:0] rf_q1;
wire   [6:0] opcode_fu_315_p1;
reg   [6:0] opcode_reg_813;
wire   [4:0] rd_fu_319_p4;
reg   [4:0] rd_reg_817;
reg   [4:0] rs1_reg_827;
reg   [4:0] rs2_reg_835;
reg   [2:0] func3_reg_841;
reg   [6:0] tmp5_reg_852;
wire  signed [31:0] sext_ln37_fu_379_p1;
reg  signed [31:0] sext_ln37_reg_857;
wire   [12:0] offset_fu_419_p6;
reg   [12:0] offset_reg_863;
wire   [31:0] imm_20_U_fu_443_p3;
reg   [31:0] imm_20_U_reg_873;
wire  signed [31:0] sext_ln42_fu_493_p1;
reg  signed [31:0] sext_ln42_reg_879;
wire   [0:0] icmp_ln57_fu_497_p2;
reg   [0:0] icmp_ln57_reg_884;
wire    ap_CS_fsm_state3;
wire   [0:0] grp_fu_300_p2;
reg   [0:0] icmp_ln88_reg_893;
wire   [31:0] next_pc_5_fu_542_p2;
wire    ap_CS_fsm_state5;
wire   [31:0] grp_fu_294_p2;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire   [31:0] next_pc_1_fu_746_p2;
wire    ap_CS_fsm_state11;
wire   [31:0] next_pc_2_fu_772_p2;
wire   [31:0] next_pc_fu_798_p2;
wire    grp_OP_AL_32I_fu_280_ap_ready;
reg   [5:0] grp_OP_AL_32I_fu_280_opcode_val;
reg   [31:0] grp_OP_AL_32I_fu_280_op1_val;
reg   [31:0] grp_OP_AL_32I_fu_280_op2_val;
wire   [31:0] grp_OP_AL_32I_fu_280_ap_return;
reg   [31:0] ap_phi_mux_next_pc_9_phi_fu_259_p18;
reg   [31:0] next_pc_9_reg_255;
reg    ap_predicate_pred140_state11;
reg    ap_predicate_pred146_state11;
reg    ap_predicate_pred151_state11;
wire   [31:0] next_pc_8_fu_516_p4;
wire    ap_CS_fsm_state4;
wire   [31:0] next_pc_7_fu_527_p4;
wire   [63:0] zext_ln86_fu_503_p1;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln87_fu_507_p1;
wire   [63:0] zext_ln82_fu_538_p1;
wire   [63:0] zext_ln77_fu_551_p1;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln72_fu_555_p1;
wire    ap_CS_fsm_state8;
wire   [63:0] zext_ln68_fu_559_p1;
wire   [63:0] zext_ln68_1_fu_563_p1;
wire   [63:0] zext_ln62_fu_567_p1;
wire   [63:0] zext_ln56_fu_571_p1;
wire   [63:0] zext_ln56_1_fu_575_p1;
wire   [63:0] zext_ln63_fu_760_p1;
reg    ap_predicate_pred212_state11;
wire   [63:0] zext_ln57_fu_786_p1;
reg    ap_predicate_pred218_state11;
wire   [31:0] add_ln77_fu_546_p2;
wire  signed [31:0] sext_ln63_fu_755_p1;
wire  signed [31:0] sext_ln57_fu_781_p1;
wire   [11:0] imm_11_0_fu_369_p4;
wire   [0:0] tmp_1_fu_391_p3;
wire   [0:0] tmp_fu_383_p3;
wire   [5:0] tmp_2_fu_409_p4;
wire   [3:0] tmp_4_fu_399_p4;
wire   [19:0] tmp_5_fu_433_p4;
wire   [7:0] tmp_8_fu_469_p4;
wire   [0:0] tmp_3_fu_461_p3;
wire   [9:0] tmp_6_fu_451_p4;
wire   [20:0] imm_JAL_fu_479_p6;
wire   [31:0] next_pc_6_fu_511_p2;
wire   [0:0] icmp_ln69_fu_579_p2;
wire   [0:0] icmp_ln70_fu_592_p2;
wire   [0:0] icmp_ln71_fu_605_p2;
wire   [0:0] icmp_ln72_fu_618_p2;
wire   [0:0] xor_ln72_fu_624_p2;
wire   [0:0] icmp_ln73_fu_637_p2;
wire   [0:0] icmp_ln74_fu_650_p2;
wire   [0:0] xor_ln74_fu_656_p2;
wire   [0:0] icmp_ln68_fu_669_p2;
wire   [12:0] returnval_6_fu_662_p3;
wire   [0:0] icmp_ln68_1_fu_682_p2;
wire   [12:0] returnval_5_fu_643_p3;
wire   [12:0] returnval_7_fu_674_p3;
wire   [0:0] icmp_ln68_2_fu_695_p2;
wire   [12:0] returnval_4_fu_630_p3;
wire   [12:0] returnval_8_fu_687_p3;
wire   [0:0] icmp_ln68_3_fu_708_p2;
wire   [12:0] returnval_3_fu_611_p3;
wire   [12:0] returnval_9_fu_700_p3;
wire   [0:0] icmp_ln68_4_fu_721_p2;
wire   [12:0] returnval_2_fu_598_p3;
wire   [12:0] returnval_10_fu_713_p3;
wire   [12:0] returnval_1_fu_585_p3;
wire   [12:0] returnval_11_fu_726_p3;
wire   [12:0] returnval_12_fu_734_p3;
wire  signed [31:0] sext_ln67_fu_742_p1;
wire   [30:0] grp_fu_305_p4;
wire   [0:0] error_1_fu_751_p1;
wire   [31:0] select_ln65_fu_764_p3;
wire   [0:0] error_fu_777_p1;
wire   [31:0] select_ln59_fu_790_p3;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
end

hart_rf_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
rf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(rf_address0),
    .ce0(rf_ce0),
    .we0(rf_we0),
    .d0(rf_d0),
    .q0(rf_q0),
    .address1(rf_address1),
    .ce1(rf_ce1),
    .we1(rf_we1),
    .d1(rf_d1),
    .q1(rf_q1)
);

hart_OP_AL_32I grp_OP_AL_32I_fu_280(
    .ap_ready(grp_OP_AL_32I_fu_280_ap_ready),
    .opcode_val(grp_OP_AL_32I_fu_280_opcode_val),
    .func7_val(tmp5_reg_852),
    .func3_val(func3_reg_841),
    .op1_val(grp_OP_AL_32I_fu_280_op1_val),
    .op2_val(grp_OP_AL_32I_fu_280_op2_val),
    .ap_return(grp_OP_AL_32I_fu_280_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln88_reg_893 == 1'd1) & (opcode_reg_813 == 7'd103) & (1'b1 == ap_CS_fsm_state4))) begin
        next_pc_9_reg_255 <= next_pc_7_fu_527_p4;
    end else if (((icmp_ln88_reg_893 == 1'd0) & (opcode_reg_813 == 7'd103) & (1'b1 == ap_CS_fsm_state4))) begin
        next_pc_9_reg_255 <= next_pc_8_fu_516_p4;
    end else if (((1'b1 == ap_CS_fsm_state11) & (ap_predicate_pred151_state11 == 1'b1))) begin
        next_pc_9_reg_255 <= next_pc_fu_798_p2;
    end else if (((1'b1 == ap_CS_fsm_state11) & (ap_predicate_pred146_state11 == 1'b1))) begin
        next_pc_9_reg_255 <= next_pc_2_fu_772_p2;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        next_pc_9_reg_255 <= grp_fu_294_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        next_pc_9_reg_255 <= next_pc_5_fu_542_p2;
    end else if (((1'b1 == ap_CS_fsm_state11) & (ap_predicate_pred140_state11 == 1'b1))) begin
        next_pc_9_reg_255 <= next_pc_1_fu_746_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_predicate_pred140_state11 <= (opcode_reg_813 == 7'd99);
        ap_predicate_pred146_state11 <= (opcode_reg_813 == 7'd19);
        ap_predicate_pred151_state11 <= (opcode_reg_813 == 7'd51);
        ap_predicate_pred212_state11 <= ((icmp_ln57_reg_884 == 1'd0) & (opcode_reg_813 == 7'd19));
        ap_predicate_pred218_state11 <= ((icmp_ln57_reg_884 == 1'd0) & (opcode_reg_813 == 7'd51));
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        func3_reg_841 <= {{inst[14:12]}};
        icmp_ln57_reg_884 <= icmp_ln57_fu_497_p2;
        imm_20_U_reg_873[31 : 12] <= imm_20_U_fu_443_p3[31 : 12];
        offset_reg_863[12 : 1] <= offset_fu_419_p6[12 : 1];
        opcode_reg_813 <= opcode_fu_315_p1;
        rd_reg_817 <= {{inst[11:7]}};
        rs1_reg_827 <= {{inst[19:15]}};
        rs2_reg_835 <= {{inst[24:20]}};
        sext_ln37_reg_857 <= sext_ln37_fu_379_p1;
        sext_ln42_reg_879[31 : 1] <= sext_ln42_fu_493_p1[31 : 1];
        tmp5_reg_852 <= {{inst[31:25]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln88_reg_893 <= grp_fu_300_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((opcode_reg_813 == 7'd103) & (1'b1 == ap_CS_fsm_state4))) begin
        if ((icmp_ln88_reg_893 == 1'd1)) begin
            ap_phi_mux_next_pc_9_phi_fu_259_p18 = next_pc_7_fu_527_p4;
        end else if ((icmp_ln88_reg_893 == 1'd0)) begin
            ap_phi_mux_next_pc_9_phi_fu_259_p18 = next_pc_8_fu_516_p4;
        end else begin
            ap_phi_mux_next_pc_9_phi_fu_259_p18 = next_pc_9_reg_255;
        end
    end else begin
        ap_phi_mux_next_pc_9_phi_fu_259_p18 = next_pc_9_reg_255;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        if ((ap_predicate_pred151_state11 == 1'b1)) begin
            grp_OP_AL_32I_fu_280_op1_val = rf_q1;
        end else if ((ap_predicate_pred146_state11 == 1'b1)) begin
            grp_OP_AL_32I_fu_280_op1_val = rf_q0;
        end else begin
            grp_OP_AL_32I_fu_280_op1_val = 'bx;
        end
    end else begin
        grp_OP_AL_32I_fu_280_op1_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        if ((ap_predicate_pred151_state11 == 1'b1)) begin
            grp_OP_AL_32I_fu_280_op2_val = rf_q0;
        end else if ((ap_predicate_pred146_state11 == 1'b1)) begin
            grp_OP_AL_32I_fu_280_op2_val = sext_ln37_reg_857;
        end else begin
            grp_OP_AL_32I_fu_280_op2_val = 'bx;
        end
    end else begin
        grp_OP_AL_32I_fu_280_op2_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        if ((ap_predicate_pred151_state11 == 1'b1)) begin
            grp_OP_AL_32I_fu_280_opcode_val = 6'd51;
        end else if ((ap_predicate_pred146_state11 == 1'b1)) begin
            grp_OP_AL_32I_fu_280_opcode_val = 6'd19;
        end else begin
            grp_OP_AL_32I_fu_280_opcode_val = 'bx;
        end
    end else begin
        grp_OP_AL_32I_fu_280_opcode_val = 'bx;
    end
end

always @ (*) begin
    if (((opcode_reg_813 == 7'd51) & (1'b1 == ap_CS_fsm_state10))) begin
        rf_address0 = zext_ln56_1_fu_575_p1;
    end else if (((opcode_reg_813 == 7'd19) & (1'b1 == ap_CS_fsm_state10))) begin
        rf_address0 = zext_ln62_fu_567_p1;
    end else if (((opcode_reg_813 == 7'd99) & (1'b1 == ap_CS_fsm_state10))) begin
        rf_address0 = zext_ln68_1_fu_563_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rf_address0 = zext_ln72_fu_555_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        rf_address0 = zext_ln77_fu_551_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        rf_address0 = zext_ln82_fu_538_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        rf_address0 = zext_ln87_fu_507_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        rf_address0 = zext_ln86_fu_503_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        rf_address0 = 5'd0;
    end else begin
        rf_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_predicate_pred218_state11 == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        rf_address1 = zext_ln57_fu_786_p1;
    end else if (((ap_predicate_pred212_state11 == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        rf_address1 = zext_ln63_fu_760_p1;
    end else if (((opcode_reg_813 == 7'd51) & (1'b1 == ap_CS_fsm_state10))) begin
        rf_address1 = zext_ln56_fu_571_p1;
    end else if (((opcode_reg_813 == 7'd99) & (1'b1 == ap_CS_fsm_state10))) begin
        rf_address1 = zext_ln68_fu_559_p1;
    end else begin
        rf_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((opcode_reg_813 == 7'd51) & (1'b1 == ap_CS_fsm_state10)) | ((opcode_reg_813 == 7'd19) & (1'b1 == ap_CS_fsm_state10)) | ((opcode_reg_813 == 7'd99) & (1'b1 == ap_CS_fsm_state10)))) begin
        rf_ce0 = 1'b1;
    end else begin
        rf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred218_state11 == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((ap_predicate_pred212_state11 == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((opcode_reg_813 == 7'd51) & (1'b1 == ap_CS_fsm_state10)) | ((opcode_reg_813 == 7'd99) & (1'b1 == ap_CS_fsm_state10)))) begin
        rf_ce1 = 1'b1;
    end else begin
        rf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        rf_d0 = imm_20_U_reg_873;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        rf_d0 = add_ln77_fu_546_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2))) begin
        rf_d0 = grp_fu_294_p2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        rf_d0 = 32'd0;
    end else begin
        rf_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        if ((ap_predicate_pred218_state11 == 1'b1)) begin
            rf_d1 = sext_ln57_fu_781_p1;
        end else if ((ap_predicate_pred212_state11 == 1'b1)) begin
            rf_d1 = sext_ln63_fu_755_p1;
        end else begin
            rf_d1 = 'bx;
        end
    end else begin
        rf_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((icmp_ln57_reg_884 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln57_reg_884 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        rf_we0 = 1'b1;
    end else begin
        rf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred218_state11 == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((ap_predicate_pred212_state11 == 1'b1) & (1'b1 == ap_CS_fsm_state11)))) begin
        rf_we1 = 1'b1;
    end else begin
        rf_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln57_fu_497_p2 == 1'd1) & (opcode_fu_315_p1 == 7'd55) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((icmp_ln57_fu_497_p2 == 1'd0) & (opcode_fu_315_p1 == 7'd55) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((icmp_ln57_fu_497_p2 == 1'd1) & (opcode_fu_315_p1 == 7'd23) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else if (((icmp_ln57_fu_497_p2 == 1'd0) & (opcode_fu_315_p1 == 7'd23) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((opcode_fu_315_p1 == 7'd111) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if (((opcode_fu_315_p1 == 7'd103) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & ((opcode_fu_315_p1 == 7'd51) | ((opcode_fu_315_p1 == 7'd19) | (opcode_fu_315_p1 == 7'd99))))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if ((~(opcode_fu_315_p1 == 7'd103) & ~(opcode_fu_315_p1 == 7'd111) & ~(opcode_fu_315_p1 == 7'd23) & ~(opcode_fu_315_p1 == 7'd55) & ~(opcode_fu_315_p1 == 7'd99) & ~(opcode_fu_315_p1 == 7'd19) & ~(opcode_fu_315_p1 == 7'd51) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln77_fu_546_p2 = (imm_20_U_reg_873 + pc);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = ap_phi_mux_next_pc_9_phi_fu_259_p18;

assign error_1_fu_751_p1 = grp_OP_AL_32I_fu_280_ap_return[0:0];

assign error_fu_777_p1 = grp_OP_AL_32I_fu_280_ap_return[0:0];

assign grp_fu_294_p2 = (pc + 32'd4);

assign grp_fu_300_p2 = ((func3_reg_841 == 3'd0) ? 1'b1 : 1'b0);

assign grp_fu_305_p4 = {{grp_OP_AL_32I_fu_280_ap_return[31:1]}};

assign icmp_ln57_fu_497_p2 = ((rd_fu_319_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln68_1_fu_682_p2 = ((func3_reg_841 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln68_2_fu_695_p2 = ((func3_reg_841 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln68_3_fu_708_p2 = ((func3_reg_841 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln68_4_fu_721_p2 = ((func3_reg_841 == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_669_p2 = ((func3_reg_841 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_579_p2 = ((rf_q1 == rf_q0) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_592_p2 = ((rf_q1 != rf_q0) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_605_p2 = (($signed(rf_q1) < $signed(rf_q0)) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_618_p2 = (($signed(rf_q1) < $signed(rf_q0)) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_637_p2 = ((rf_q1 < rf_q0) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_650_p2 = ((rf_q1 < rf_q0) ? 1'b1 : 1'b0);

assign imm_11_0_fu_369_p4 = {{inst[31:20]}};

assign imm_20_U_fu_443_p3 = {{tmp_5_fu_433_p4}, {12'd0}};

assign imm_JAL_fu_479_p6 = {{{{{tmp_1_fu_391_p3}, {tmp_8_fu_469_p4}}, {tmp_3_fu_461_p3}}, {tmp_6_fu_451_p4}}, {1'd0}};

assign next_pc_1_fu_746_p2 = ($signed(sext_ln67_fu_742_p1) + $signed(pc));

assign next_pc_2_fu_772_p2 = (select_ln65_fu_764_p3 + pc);

assign next_pc_5_fu_542_p2 = ($signed(sext_ln42_reg_879) + $signed(pc));

assign next_pc_6_fu_511_p2 = ($signed(rf_q0) + $signed(sext_ln37_reg_857));

assign next_pc_7_fu_527_p4 = {next_pc_6_fu_511_p2[32-1:1], |(1'd0)};

assign next_pc_8_fu_516_p4 = {next_pc_6_fu_511_p2[32-1:1], |(1'd1)};

assign next_pc_fu_798_p2 = (select_ln59_fu_790_p3 + pc);

assign offset_fu_419_p6 = {{{{{tmp_1_fu_391_p3}, {tmp_fu_383_p3}}, {tmp_2_fu_409_p4}}, {tmp_4_fu_399_p4}}, {1'd0}};

assign opcode_fu_315_p1 = inst[6:0];

assign rd_fu_319_p4 = {{inst[11:7]}};

assign returnval_10_fu_713_p3 = ((icmp_ln68_3_fu_708_p2[0:0] == 1'b1) ? returnval_3_fu_611_p3 : returnval_9_fu_700_p3);

assign returnval_11_fu_726_p3 = ((icmp_ln68_4_fu_721_p2[0:0] == 1'b1) ? returnval_2_fu_598_p3 : returnval_10_fu_713_p3);

assign returnval_12_fu_734_p3 = ((grp_fu_300_p2[0:0] == 1'b1) ? returnval_1_fu_585_p3 : returnval_11_fu_726_p3);

assign returnval_1_fu_585_p3 = ((icmp_ln69_fu_579_p2[0:0] == 1'b1) ? offset_reg_863 : 13'd4);

assign returnval_2_fu_598_p3 = ((icmp_ln70_fu_592_p2[0:0] == 1'b1) ? offset_reg_863 : 13'd4);

assign returnval_3_fu_611_p3 = ((icmp_ln71_fu_605_p2[0:0] == 1'b1) ? offset_reg_863 : 13'd4);

assign returnval_4_fu_630_p3 = ((xor_ln72_fu_624_p2[0:0] == 1'b1) ? offset_reg_863 : 13'd4);

assign returnval_5_fu_643_p3 = ((icmp_ln73_fu_637_p2[0:0] == 1'b1) ? offset_reg_863 : 13'd4);

assign returnval_6_fu_662_p3 = ((xor_ln74_fu_656_p2[0:0] == 1'b1) ? offset_reg_863 : 13'd4);

assign returnval_7_fu_674_p3 = ((icmp_ln68_fu_669_p2[0:0] == 1'b1) ? returnval_6_fu_662_p3 : 13'd1);

assign returnval_8_fu_687_p3 = ((icmp_ln68_1_fu_682_p2[0:0] == 1'b1) ? returnval_5_fu_643_p3 : returnval_7_fu_674_p3);

assign returnval_9_fu_700_p3 = ((icmp_ln68_2_fu_695_p2[0:0] == 1'b1) ? returnval_4_fu_630_p3 : returnval_8_fu_687_p3);

assign select_ln59_fu_790_p3 = ((error_fu_777_p1[0:0] == 1'b1) ? 32'd5 : 32'd4);

assign select_ln65_fu_764_p3 = ((error_1_fu_751_p1[0:0] == 1'b1) ? 32'd5 : 32'd4);

assign sext_ln37_fu_379_p1 = $signed(imm_11_0_fu_369_p4);

assign sext_ln42_fu_493_p1 = $signed(imm_JAL_fu_479_p6);

assign sext_ln57_fu_781_p1 = $signed(grp_fu_305_p4);

assign sext_ln63_fu_755_p1 = $signed(grp_fu_305_p4);

assign sext_ln67_fu_742_p1 = $signed(returnval_12_fu_734_p3);

assign tmp_1_fu_391_p3 = inst[32'd31];

assign tmp_2_fu_409_p4 = {{inst[30:25]}};

assign tmp_3_fu_461_p3 = inst[32'd20];

assign tmp_4_fu_399_p4 = {{inst[11:8]}};

assign tmp_5_fu_433_p4 = {{inst[31:12]}};

assign tmp_6_fu_451_p4 = {{inst[30:21]}};

assign tmp_8_fu_469_p4 = {{inst[19:12]}};

assign tmp_fu_383_p3 = inst[32'd7];

assign xor_ln72_fu_624_p2 = (icmp_ln72_fu_618_p2 ^ 1'd1);

assign xor_ln74_fu_656_p2 = (icmp_ln74_fu_650_p2 ^ 1'd1);

assign zext_ln56_1_fu_575_p1 = rs2_reg_835;

assign zext_ln56_fu_571_p1 = rs1_reg_827;

assign zext_ln57_fu_786_p1 = rd_reg_817;

assign zext_ln62_fu_567_p1 = rs1_reg_827;

assign zext_ln63_fu_760_p1 = rd_reg_817;

assign zext_ln68_1_fu_563_p1 = rs2_reg_835;

assign zext_ln68_fu_559_p1 = rs1_reg_827;

assign zext_ln72_fu_555_p1 = rd_reg_817;

assign zext_ln77_fu_551_p1 = rd_reg_817;

assign zext_ln82_fu_538_p1 = rd_reg_817;

assign zext_ln86_fu_503_p1 = rd_reg_817;

assign zext_ln87_fu_507_p1 = rs1_reg_827;

always @ (posedge ap_clk) begin
    offset_reg_863[0] <= 1'b0;
    imm_20_U_reg_873[11:0] <= 12'b000000000000;
    sext_ln42_reg_879[0] <= 1'b0;
end

endmodule //hart
